import dayjs, { type Dayjs } from 'dayjs';
import type { ScheduleRow, ChecklistSession, EquipmentOption } from './types';

export const mockEquipmentsList: EquipmentOption[] = [
  { id: 'eq-cnc-01', code: 'EQ-CNC-01', name: 'Máy phay CNC Haas UMC-750' },
  { id: 'eq-robot-02', code: 'EQ-ROBOT-02', name: 'Cánh tay Robot hàn FANUC ARC Mate' },
  { id: 'eq-press-03', code: 'EQ-PRESS-03', name: 'Máy dập thủy lực Komatsu 200T' },
  { id: 'eq-comp-04', code: 'EQ-COMP-04', name: 'Máy nén khí Atlas Copco GA37' },
  { id: 'eq-inj-05', code: 'EQ-INJ-05', name: 'Máy ép nhựa Sumitomo SE180EV' },
  { id: 'eq-conv-06', code: 'EQ-CONV-06', name: 'Băng tải phân loại Siemens' },
  { id: 'eq-plc-07', code: 'EQ-PLC-07', name: 'Tủ điều khiển trung tâm PLC S7-1500' },
];

export function getMockSchedules(baseDate: Dayjs): ScheduleRow[] {
  const d = (dayOffset: number) => baseDate.date(1).add(dayOffset, 'day').format('YYYY-MM-DD');

  return [
    {
      id: 'sch-mock-01',
      plan_code: 'MP-CNC-01',
      date: d(1),
      result: 'pass',
      equipment_id: 'eq-cnc-01',
      equipment_code: 'EQ-CNC-01',
      equipment_name: 'EQ-CNC-01 — Máy phay CNC Haas UMC-750',
      category_name: 'Bảo trì máy CNC',
      item_name: 'Thay dầu thủy lực & vệ sinh bồn chứa',
      item_description: 'Kiểm tra van áp suất, thay phớt bôi trơn và xả cặn dầu nhớt',
      maintenance_type: 'Hàng tuần',
      user_ids: ['u-01'],
      users: [{ id: 'u-01', name: 'Nguyễn Văn Hùng', email: 'hung.nguyen@company.com' }],
      maintenance_plan_id: 'plan-cnc-01',
      maintenance_plan: {
        plan_code: 'MP-CNC-01',
        equipment_id: 'eq-cnc-01',
        maintenance_type: 'Hàng tuần',
        equipment: { code: 'EQ-CNC-01', name: 'Máy phay CNC Haas UMC-750' },
        maintenance_category: { name: 'Bảo trì máy CNC' },
      },
      maintenance_item: {
        name: 'Thay dầu thủy lực & vệ sinh bồn chứa',
        description: 'Kiểm tra van áp suất, thay phớt bôi trơn và xả cặn dầu nhớt',
      },
    },
    {
      id: 'sch-mock-02',
      plan_code: 'MP-ROBOT-02',
      date: d(4),
      result: 'pass',
      equipment_id: 'eq-robot-02',
      equipment_code: 'EQ-ROBOT-02',
      equipment_name: 'EQ-ROBOT-02 — Cánh tay Robot hàn FANUC ARC Mate',
      category_name: 'Bảo trì Robot tự động',
      item_name: 'Hiệu chỉnh khớp xoay & kiểm tra mắt thần',
      item_description: 'Vệ sinh đầu mỏ hàn, căng dây cáp tín hiệu và đo sai số quỹ đạo',
      maintenance_type: 'Hàng tháng',
      user_ids: ['u-02'],
      users: [{ id: 'u-02', name: 'Trần Quốc Bảo', email: 'bao.tran@company.com' }],
      maintenance_plan_id: 'plan-robot-02',
      maintenance_plan: {
        plan_code: 'MP-ROBOT-02',
        equipment_id: 'eq-robot-02',
        maintenance_type: 'Hàng tháng',
        equipment: { code: 'EQ-ROBOT-02', name: 'Cánh tay Robot hàn FANUC ARC Mate' },
        maintenance_category: { name: 'Bảo trì Robot tự động' },
      },
      maintenance_item: {
        name: 'Hiệu chỉnh khớp xoay & kiểm tra mắt thần',
        description: 'Vệ sinh đầu mỏ hàn, căng dây cáp tín hiệu và đo sai số quỹ đạo',
      },
    },
    {
      id: 'sch-mock-03',
      plan_code: 'MP-PRESS-03',
      date: d(8),
      result: null,
      equipment_id: 'eq-press-03',
      equipment_code: 'EQ-PRESS-03',
      equipment_name: 'EQ-PRESS-03 — Máy dập thủy lực Komatsu 200T',
      category_name: 'Bảo trì máy dập',
      item_name: 'Kiểm tra lực ép & gioăng phớt xi lanh',
      item_description: 'Kiểm tra độ cân bằng bàn dập, xiết ốc chân đế và thay bộ lọc dầu',
      maintenance_type: 'Hàng tháng',
      user_ids: ['u-03'],
      users: [{ id: 'u-03', name: 'Lê Minh Đức', email: 'duc.le@company.com' }],
      maintenance_plan_id: 'plan-press-03',
      maintenance_plan: {
        plan_code: 'MP-PRESS-03',
        equipment_id: 'eq-press-03',
        maintenance_type: 'Hàng tháng',
        equipment: { code: 'EQ-PRESS-03', name: 'Máy dập thủy lực Komatsu 200T' },
        maintenance_category: { name: 'Bảo trì máy dập' },
      },
      maintenance_item: {
        name: 'Kiểm tra lực ép & gioăng phớt xi lanh',
        description: 'Kiểm tra độ cân bằng bàn dập, xiết ốc chân đế và thay bộ lọc dầu',
      },
    },
    {
      id: 'sch-mock-04',
      plan_code: 'MP-COMP-04',
      date: d(12),
      result: 'pass',
      equipment_id: 'eq-comp-04',
      equipment_code: 'EQ-COMP-04',
      equipment_name: 'EQ-COMP-04 — Máy nén khí Atlas Copco GA37',
      category_name: 'Hệ thống khí nén',
      item_name: 'Thay bộ lọc gió & kiểm tra van an toàn',
      item_description: 'Xả nước ngưng tụ, đo dòng điện động cơ và kiểm tra áp suất xả',
      maintenance_type: 'Hàng tuần',
      user_ids: ['u-01', 'u-04'],
      users: [
        { id: 'u-01', name: 'Nguyễn Văn Hùng', email: 'hung.nguyen@company.com' },
        { id: 'u-04', name: 'Phạm Hoàng Nam', email: 'nam.pham@company.com' }
      ],
      maintenance_plan_id: 'plan-comp-04',
      maintenance_plan: {
        plan_code: 'MP-COMP-04',
        equipment_id: 'eq-comp-04',
        maintenance_type: 'Hàng tuần',
        equipment: { code: 'EQ-COMP-04', name: 'Máy nén khí Atlas Copco GA37' },
        maintenance_category: { name: 'Hệ thống khí nén' },
      },
      maintenance_item: {
        name: 'Thay bộ lọc gió & kiểm tra van an toàn',
        description: 'Xả nước ngưng tụ, đo dòng điện động cơ và kiểm tra áp suất xả',
      },
    },
    {
      id: 'sch-mock-05',
      plan_code: 'MP-INJ-05',
      date: d(16),
      result: null,
      equipment_id: 'eq-inj-05',
      equipment_code: 'EQ-INJ-05',
      equipment_name: 'EQ-INJ-05 — Máy ép nhựa Sumitomo SE180EV',
      category_name: 'Bảo trì máy ép nhựa',
      item_name: 'Vệ sinh trục vít & gia nhiệt nòng khuôn',
      item_description: 'Đo điện trở gia nhiệt, vệ sinh cổng xả nhựa và bôi trơn ty đẩy',
      maintenance_type: 'Hàng tháng',
      user_ids: ['u-05'],
      users: [{ id: 'u-05', name: 'Trịnh Văn Vũ', email: 'vu.trinh@company.com' }],
      maintenance_plan_id: 'plan-inj-05',
      maintenance_plan: {
        plan_code: 'MP-INJ-05',
        equipment_id: 'eq-inj-05',
        maintenance_type: 'Hàng tháng',
        equipment: { code: 'EQ-INJ-05', name: 'Máy ép nhựa Sumitomo SE180EV' },
        maintenance_category: { name: 'Bảo trì máy ép nhựa' },
      },
      maintenance_item: {
        name: 'Vệ sinh trục vít & gia nhiệt nòng khuôn',
        description: 'Đo điện trở gia nhiệt, vệ sinh cổng xả nhựa và bôi trơn ty đẩy',
      },
    },
    {
      id: 'sch-mock-06',
      plan_code: 'MP-CONV-06',
      date: d(20),
      result: 'pass',
      equipment_id: 'eq-conv-06',
      equipment_code: 'EQ-CONV-06',
      equipment_name: 'EQ-CONV-06 — Băng tải phân loại Siemens',
      category_name: 'Băng tải truyền động',
      item_name: 'Tăng sên truyền động & kiểm tra động cơ giảm tốc',
      item_description: 'Căn chỉnh độ căng con lăn, kiểm tra cảm biến phát hiện hàng',
      maintenance_type: 'Hàng tuần',
      user_ids: ['u-02'],
      users: [{ id: 'u-02', name: 'Trần Quốc Bảo', email: 'bao.tran@company.com' }],
      maintenance_plan_id: 'plan-conv-06',
      maintenance_plan: {
        plan_code: 'MP-CONV-06',
        equipment_id: 'eq-conv-06',
        maintenance_type: 'Hàng tuần',
        equipment: { code: 'EQ-CONV-06', name: 'Băng tải phân loại Siemens' },
        maintenance_category: { name: 'Băng tải truyền động' },
      },
      maintenance_item: {
        name: 'Tăng sên truyền động & kiểm tra động cơ giảm tốc',
        description: 'Căn chỉnh độ căng con lăn, kiểm tra cảm biến phát hiện hàng',
      },
    },
    {
      id: 'sch-mock-07',
      plan_code: 'MP-PLC-07',
      date: d(25),
      result: null,
      equipment_id: 'eq-plc-07',
      equipment_code: 'EQ-PLC-07',
      equipment_name: 'EQ-PLC-07 — Tủ điều khiển trung tâm PLC S7-1500',
      category_name: 'Hệ thống điện & Điều khiển',
      item_name: 'Bảo dưỡng tủ điện & vệ sinh quạt tản nhiệt',
      item_description: 'Xiết chặt các cầu đấu dây, xịt bụi bộ nguồn 24V và backup phần mềm PLC',
      maintenance_type: 'Hàng tháng',
      user_ids: ['u-03'],
      users: [{ id: 'u-03', name: 'Lê Minh Đức', email: 'duc.le@company.com' }],
      maintenance_plan_id: 'plan-plc-07',
      maintenance_plan: {
        plan_code: 'MP-PLC-07',
        equipment_id: 'eq-plc-07',
        maintenance_type: 'Hàng tháng',
        equipment: { code: 'EQ-PLC-07', name: 'Tủ điều khiển trung tâm PLC S7-1500' },
        maintenance_category: { name: 'Hệ thống điện & Điều khiển' },
      },
      maintenance_item: {
        name: 'Bảo dưỡng tủ điện & vệ sinh quạt tản nhiệt',
        description: 'Xiết chặt các cầu đấu dây, xịt bụi bộ nguồn 24V và backup phần mềm PLC',
      },
    },
  ];
}

export function getMockChecklistSessions(baseDate: Dayjs): ChecklistSession[] {
  const d = (dayOffset: number) => baseDate.date(1).add(dayOffset, 'day').format('YYYY-MM-DD');

  return [
    {
      id: 'chk-mock-01',
      name: 'Checklist ca sáng - Máy CNC Haas UMC-750',
      equipment_id: 'eq-cnc-01',
      equipment: { id: 'eq-cnc-01', code: 'EQ-CNC-01', name: 'Máy phay CNC Haas UMC-750' },
      session_date: d(1),
      cycle_type: 'daily',
      details: [
        { id: 'cd-1', checklist_id: 'chk-mock-01', description: 'Kiểm tra mức dầu bôi trơn đường dẫn hướng Z/X/Y', logs: [{ id: 'l1', status: 'completed', result: 'pass', checked_at: `${d(1)} 07:30:00` }] },
        { id: 'cd-2', checklist_id: 'chk-mock-01', description: 'Kiểm tra áp suất khí nén đầu vào (chuẩn 6-8 bar)', logs: [{ id: 'l2', status: 'completed', result: 'pass', checked_at: `${d(1)} 07:32:00` }] },
        { id: 'cd-3', checklist_id: 'chk-mock-01', description: 'Kiểm tra mức nước làm mát trục chính', logs: [{ id: 'l3', status: 'completed', result: 'pass', checked_at: `${d(1)} 07:35:00` }] },
      ],
      users: [{ id: 'u-01', name: 'Nguyễn Văn Hùng' }],
    },
    {
      id: 'chk-mock-02',
      name: 'Checklist kiểm tra Robot hàn FANUC',
      equipment_id: 'eq-robot-02',
      equipment: { id: 'eq-robot-02', code: 'EQ-ROBOT-02', name: 'Cánh tay Robot hàn FANUC ARC Mate' },
      session_date: d(3),
      cycle_type: 'daily',
      details: [
        { id: 'cd-4', checklist_id: 'chk-mock-02', description: 'Vệ sinh mỏ hàn & đầu phun chống dính xỉ hàn', logs: [{ id: 'l4', status: 'completed', result: 'pass', checked_at: `${d(3)} 08:00:00` }] },
        { id: 'cd-5', checklist_id: 'chk-mock-02', description: 'Kiểm tra tình trạng dây cấp dây hàn & bình khí CO2/Argon', logs: [{ id: 'l5', status: 'completed', result: 'pass', checked_at: `${d(3)} 08:05:00` }] },
      ],
      users: [{ id: 'u-02', name: 'Trần Quốc Bảo' }],
    },
    {
      id: 'chk-mock-03',
      name: 'Checklist an toàn ca dập Komatsu 200T',
      equipment_id: 'eq-press-03',
      equipment: { id: 'eq-press-03', code: 'EQ-PRESS-03', name: 'Máy dập thủy lực Komatsu 200T' },
      session_date: d(7),
      cycle_type: 'daily',
      details: [
        { id: 'cd-6', checklist_id: 'chk-mock-03', description: 'Kiểm tra cảm biến quang an toàn (Light curtain)', logs: [{ id: 'l6', status: 'completed', result: 'pass', checked_at: `${d(7)} 07:45:00` }] },
        { id: 'cd-7', checklist_id: 'chk-mock-03', description: 'Thử nút dừng khẩn cấp E-Stop', logs: [{ id: 'l7', status: 'completed', result: 'pass', checked_at: `${d(7)} 07:46:00` }] },
        { id: 'cd-8', checklist_id: 'chk-mock-03', description: 'Kiểm tra độ rò rỉ dầu van điều hướng xi lanh', logs: [{ id: 'l8', status: 'pending', result: null }] },
      ],
      users: [{ id: 'u-03', name: 'Lê Minh Đức' }],
    },
    {
      id: 'chk-mock-04',
      name: 'Kiểm tra vận hành Máy nén khí Atlas Copco',
      equipment_id: 'eq-comp-04',
      equipment: { id: 'eq-comp-04', code: 'EQ-COMP-04', name: 'Máy nén khí Atlas Copco GA37' },
      session_date: d(11),
      cycle_type: 'daily',
      details: [
        { id: 'cd-9', checklist_id: 'chk-mock-04', description: 'Xả nước xả tự động bồn chứa khí nén', logs: [{ id: 'l9', status: 'completed', result: 'pass', checked_at: `${d(11)} 08:15:00` }] },
        { id: 'cd-10', checklist_id: 'chk-mock-04', description: 'Kiểm tra nhiệt độ đầu nén (giới hạn < 95°C)', logs: [{ id: 'l10', status: 'completed', result: 'pass', checked_at: `${d(11)} 08:20:00` }] },
      ],
      users: [{ id: 'u-04', name: 'Phạm Hoàng Nam' }],
    },
    {
      id: 'chk-mock-05',
      name: 'Checklist ca sản xuất Máy ép nhựa Sumitomo',
      equipment_id: 'eq-inj-05',
      equipment: { id: 'eq-inj-05', code: 'EQ-INJ-05', name: 'Máy ép nhựa Sumitomo SE180EV' },
      session_date: d(15),
      cycle_type: 'daily',
      details: [
        { id: 'cd-11', checklist_id: 'chk-mock-05', description: 'Kiểm tra nhiệt độ 4 vùng gia nhiệt nòng khuôn', logs: [{ id: 'l11', status: 'completed', result: 'pass', checked_at: `${d(15)} 07:10:00` }] },
        { id: 'cd-12', checklist_id: 'chk-mock-05', description: 'Kiểm tra lực kẹp khuôn (Tonnage display)', logs: [{ id: 'l12', status: 'completed', result: 'pass', checked_at: `${d(15)} 07:15:00` }] },
      ],
      users: [{ id: 'u-05', name: 'Trịnh Văn Vũ' }],
    },
    {
      id: 'chk-mock-06',
      name: 'Checklist định kỳ Băng tải phân loại Siemens',
      equipment_id: 'eq-conv-06',
      equipment: { id: 'eq-conv-06', code: 'EQ-CONV-06', name: 'Băng tải phân loại Siemens' },
      session_date: d(19),
      cycle_type: 'daily',
      details: [
        { id: 'cd-13', checklist_id: 'chk-mock-06', description: 'Kiểm tra độ đảo cuộn rulo truyền động', logs: [{ id: 'l13', status: 'completed', result: 'pass', checked_at: `${d(19)} 08:30:00` }] },
        { id: 'cd-14', checklist_id: 'chk-mock-06', description: 'Kiểm tra độ nhạy cảm biến photo-sensor phân loại', logs: [{ id: 'l14', status: 'completed', result: 'pass', checked_at: `${d(19)} 08:35:00` }] },
      ],
      users: [{ id: 'u-02', name: 'Trần Quốc Bảo' }],
    },
    {
      id: 'chk-mock-07',
      name: 'Checklist tủ điện trung tâm PLC S7-1500',
      equipment_id: 'eq-plc-07',
      equipment: { id: 'eq-plc-07', code: 'EQ-PLC-07', name: 'Tủ điều khiển trung tâm PLC S7-1500' },
      session_date: d(24),
      cycle_type: 'daily',
      details: [
        { id: 'cd-15', checklist_id: 'chk-mock-07', description: 'Kiểm tra nhiệt độ bên trong tủ điện (< 40°C)', logs: [{ id: 'l15', status: 'completed', result: 'pass', checked_at: `${d(24)} 09:00:00` }] },
        { id: 'cd-16', checklist_id: 'chk-mock-07', description: 'Kiểm tra đèn báo trạng thái module I/O PLC', logs: [{ id: 'l16', status: 'completed', result: 'pass', checked_at: `${d(24)} 09:05:00` }] },
      ],
      users: [{ id: 'u-03', name: 'Lê Minh Đức' }],
    },
  ];
}
